name: bibleguessr-production

services:
  nginx:
    image: docker.io/isuperman/bibleguessr-nginx:${VERSION:?VERSION must be set (load env/app.env)}
    logging:
      driver: ${NGINX_LOGGING_DRIVER:-json-file}
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ${LETSENCRYPT_CHALLENGES_DIR:?LETSENCRYPT_CHALLENGES_DIR must be set (load env/letsencrypt.env)}:/var/www/letsencrypt_challenges
      - ${LETSENCRYPT_DIR:?LETSENCRYPT_DIR must be set (load env/letsencrypt.env)}:/etc/letsencrypt:ro
      - ${NGINX_DIR:?NGINX_DIR must be set (load env/nginx.env)}:/etc/nginx/
    env_file:
      - ./env/nginx.env
      - ./env/app.env
      - ./env/letsencrypt.env
    # depends_on:
    #   - web-api
    #   - yarp
    networks:
      - bibleguessr-prod
    restart: unless-stopped

  bibleguessr-api:
    image: docker.io/isuperman/bibleguessr-api:${VERSION:?VERSION must be set (load env/app.env)}
    env_file:
      - ./env/bibleguessr/brevo.env
      - ./env/webapi.env
      - ./env/app.env
    volumes:
      - ./bibles/bibelen-dk/src:/app/bibles/bibelen-dk/src:ro
    networks:
      - bibleguessr-prod
    restart: unless-stopped

networks:
  bibleguessr-prod:
    driver: bridge
