version: "3"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all

includes:
  dev:
    taskfile: ./Taskfile.Development.yml
  docker:
    taskfile: ./Taskfile.Docker.yml
