server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name vault.kforkode.dk www.vault.kforkode.dk;

  ssl_certificate /etc/letsencrypt/live/vault.kforkode.dk/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/vault.kforkode.dk/privkey.pem;

  location = / {
    default_type text/plain;
    return 200 "HTTPS test OK (vault.kforkode.dk)\n";
  }

  location /.well-known/acme-challenge/ {
    root /var/www/letsencrypt_challenges;
  }
}
