worker_processes 1;
events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Global definitions used by server blocks and locations
    include includes/http-globals.conf;

    # Include modular configuration files
    include conf.d/*.conf;
}
