# Handling header-less scans
# Catch-all: HTTP
server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    server_name _;
    include includes/security-checks.conf;
    return      444;
}
# Catch-all: drop ukendte forbindelser på 443 (porscannere, SNI-sniffing)
server {
    listen      443 ssl default_server;
    listen      [::]:443 ssl default_server;
    server_name _;

    include includes/security-checks.conf;

    ssl_certificate     ssl/dummy.crt;
    ssl_certificate_key ssl/dummy.key;

    return      444;
}
