# Global definitions used by server blocks and locations
resolver 127.0.0.11 valid=10s ipv6=off;

include includes/log-formats.conf;
include includes/good-guys.conf;
include includes/bad-guys.conf;
include includes/rate-limiting.conf;
include includes/upstreams.conf;
