# Security location for suspicious paths
location ~* ^/(dns-query|query|resolve)(\?|$) {
    default_type text/plain;
    alias /usr/share/nginx/html/the-forbidden-zone/production.conf;
    add_header Content-Disposition "attachment; filename=production.conf";
    limit_rate 10k;
}

# Block access to sensitive files
location ~* ^/(\.env|config(\.js|\.env|\.yml)|phpunit|eval-stdin\.php|aws/credentials|aws/iam|shared/|vendor/|objects/|\.git|\.htaccess|\.DS_Store|\.svn|\.idea|composer\.json|package\.json|yarn\.lock|node_modules) {
    default_type text/plain;
    alias /usr/share/nginx/html/the-forbidden-zone/production.conf;
    add_header Content-Disposition "attachment; filename=production.conf";
    limit_rate 10k;
    access_log off;
}